# Generated by Django 2.2.1 on 2019-07-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondissue',
            name='IssuedAmount',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bondissue',
            name='OutstandingAmount',
            field=models.BigIntegerField(blank=True),
        ),
    ]
