# Generated by Django 2.2.1 on 2019-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190709_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='abbr',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
