# Generated by Django 2.2.1 on 2019-07-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190719_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondissue',
            name='BidPrice',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
    ]
